import "./wall"

import "./modules/teleport"
import "./modules/pets"
import "./modules/puzzles"
import "./modules/tps"
import "./modules/lag"
import "./modules/lostToLag"
import "./modules/wardrobe"
import "./modules/chestClicked"
import "./modules/leverClicked"